###
GET {{protocol}}{{host}}/q/health

###
GET {{protocol}}{{host}}/q/info

### abbdd14d-9dfb-434d-8696-fbffa0d52d5d Леопольд
### 370c779a-3570-49e4-b066-34f1c06f494d Леонардо
POST {{protocol}}{{host}}/login
Content-Type: application/json

{
  "id": "abbdd14d-9dfb-434d-8696-fbffa0d52d5d",
  "password": "123"
}



> {%
    client.global.set("auth_token", response.body.token);
%}

###
GET {{protocol}}{{host}}/post/feed?offset=0&limit=100
Content-Type: application/json
Authorization: Bearer {{auth_token}}


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
POST {{protocol}}{{host}}/post/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "text": "new text"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
